desc = "Replace small numbers with zero"
license = "MIT"
authors = ["John Lapeyre <lapeyre.math122a@gmail.com>"]
name = "ZChop"
uuid = "b27edb18-8610-11e8-0ff7-3b887cacc5ac"
version = "0.3.0+"

[deps]
